import type { Metadata } from "next";
import "./globals.css";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import localFont from "next/font/local";

// Import fonts directly
const montExtraLight = localFont({
  src: "./fonts/Mont-ExtraLightDEMO.otf",
  weight: "200",
  style: "normal",
});

// const montHeavy = localFont({
//   src: "./fonts/Mont-HeavyDEMO.otf",
//   weight: "900",
//   style: "normal",
// });

export const metadata: Metadata = {
  title: "Ryfitout - Design & Build Firm",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${montExtraLight.className} `}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
